packer {
  required_plugins {
    ansible = {
      source  = "github.com/hashicorp/ansible"
      version = "~> 1"
    }
    docker = {
      source  = "github.com/hashicorp/docker"
      version = "~> 1"
    }
  }
}

variable "image_from" {
  type    = string
  default = "alpine:latest"
}

variable "named_version" {
  type    = string
  default = "9.18.29"
}

variable "named_confdir" {
  type    = string
  default = "/etc/named"
}

variable "named_datadir" {
  type    = string
  default = "/var/named"
}

variable "named_root" {
  type    = string
  default = "/chroot"
}

variable "named_user" {
  type    = string
  default = "named"
}

variable "timezone" {
  type    = string
  default = "Asia/Tokyo"
}

source "docker" "autogenerated_1" {
  image       = var.image_from
  run_command = ["-dit", "{{ .Image }}", "/bin/ash"]
  commit      = true
}

build {
  sources = ["source.docker.autogenerated_1"]

  provisioner "shell" {
    inline = [
      "apk update",
      "apk upgrade --update --available",
      "apk add --no-cache ansible python3 xz",
      "mkdir -p /tmp/ansible-local"
    ]
  }

  provisioner "file" {
    source      = "files/"
    destination = "/tmp/ansible-local/"
  }

  provisioner "ansible-local" {
    playbook_file = "baseimage.yml"
    staging_directory = "/tmp/ansible-local"
    extra_arguments = [
      "-e timezone=${var.timezone}",
      "-e named_root=${var.named_root}",
      "-e named_user=${var.named_user}",
      "-e named_confdir=${var.named_confdir}",
      "-e named_datadir=${var.named_datadir}",
      "-e named_version=${var.named_version}",
      "-e ansible_python_interpreter=/usr/bin/python3"
    ]
  }

  post-processor "docker-tag" {
    repository = "autechgemz/named"
    tags       = ["latest"]
  }
}

