---
- name: Ansible Provision
  hosts: all
  tasks:
  - name: setup named
    block:
    - name: "generate named configration"
      file:
        path: "{{ item }}"
        owner: "{{ named_user }}"
        group: "{{ named_user }}"
        mode: 0755
        state: directory
      with_items:
        - "{{ named_root }}{{named_confdir }}"
        - "{{ named_root }}{{named_confdir }}/conf.d"
    - template:
        src: etc/named/named.conf
        dest: "{{ named_root }}{{ named_confdir }}/named.conf"
        owner: "{{ named_user }}"
        group: "{{ named_user }}" 
        mode: 0755
    - template:
        src: etc/named/conf.d/logging.conf
        dest: "{{ named_root }}{{ named_confdir }}/conf.d/logging.conf"
        owner: "{{ named_user }}"
        group: "{{ named_user }}"
        mode: 0755
    - template:
        src: etc/named/conf.d/acl.conf
        dest: "{{ named_root }}{{ named_confdir }}/conf.d/acl.conf"
        owner: "{{ named_user }}"
        group: "{{ named_user }}"
        mode: 0755
    - template:
        src: etc/named/conf.d/options.conf
        dest: "{{ named_root }}{{ named_confdir }}/conf.d/options.conf"
        owner: "{{ named_user }}"
        group: "{{ named_user }}"
        mode: 0755
    - template:
        src: etc/named/conf.d/zone-external.conf
        dest: "{{ named_root }}{{ named_confdir }}/conf.d/zone-external.conf"
        owner: "{{ named_user }}"
        group: "{{ named_user }}"
        mode: 0755
    - template:
        src: etc/named/conf.d/zone-internal.conf
        dest: "{{ named_root }}{{ named_confdir }}/conf.d/zone-internal.conf"
        owner: "{{ named_user }}"
        group: "{{ named_user }}"
        mode: 0755
    - name: "copy {{ named_root }}{{ named_datadir }}"
      copy:
        src: var/named/
        dest: "{{ named_root }}{{ named_datadir }}"
        owner: "{{ named_user }}"
        group: "{{ named_user }}"
        mode: 0755
    - name: create device directory
      file:
        path: "{{ named_root }}/dev"
        state: directory
        owner: "{{ named_user }}"
        group: "{{ named_user }}"
        mode: 0755
    - name: make devices
      shell: |
        mknod {{ named_root }}/dev/random c 1 8 \
        && mknod {{ named_root }}/dev/null c 1 3 \
        && chown -R named.named {{ named_root }}
  - name: setup runit service
    block:
    - name: copy service directory
      copy:
        src: services/
        dest: /services
        owner: root
        group: root
        mode: 0755
