version: "3"
services:
  named:
    image: autechgemz/named
    container_name: named
    network_mode: host
    restart: always
    healthcheck:
      test: ["CMD","dig","@localhost","localhost","+norec"]
      interval: 5m
      timeout: 10s
      retries: 3
    environment:
      TZ: "Asia/Tokyo"
