version: "3"
services:
  named:
    image: autechgemz/named
    container_name: named
    hostname: named
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      RUN_DNSTAP: "true"
