name: build-named

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master      
  workflow_dispatch:
    inputs:
      no-cache:
        description: "Build docker images with no cache"
        default: false
        required: false
        type: boolean

env:
  NAMED_VERSION: 9.18.14
  TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Image
        run: make

      - name: Push Image
        run: make push

  check:
    needs: [ build ]
    runs-on: ubuntu-latest
    outputs:
      named-bin: ${{ steps.named.outputs.stdout }}
    steps:
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run named
        run: docker run --rm -t -d named autechgemz/named:latest

      - name: Check named
        id: named-bin
        run: docker run --rm -t --entrypoint "" autechgemz/named:latest /chroot/sbin/named -V

      - name: Check named-checkconf
        run: docker exec -t named named-checkconf -t /chroot /etc/named/named.conf

  clean:
    needs: [ check ]
    runs-on: ubuntu-latest
    steps:
      - name: Remove named
        runs: |
          docker rmi -f autechgemz/named:latest
          docker images
        shell: bash

